MyWebApp/Models/Member.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace MyWebApp.Models
{
    public class Member
    {
        public int Id { get; set; }

        [Required]
        [StringLength(60, MinimumLength = 1)]
        [Display(Name = "姓名")]
        public string Name { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "密碼")]
        public string Password { get; set; }


        public string Role { get; set; }

        public Member()
        {

        }
        public Member(int id, string name, string email, string password)
        {
            Id = id;
            Name = name;
            Email = email;
            Password = password;
        }
    }
}

MyWebApp/Controllers/JokesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyWebApp.Data;
using MyWebApp.Models;

namespace MyWebApp.Controllers
{
    public class JokesController : Controller
    {
        private readonly MyWebAppDbContext _context;

        public JokesController(MyWebAppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            List<Joke> resultList = new List<Joke>();
            
            if (User.Identity.IsAuthenticated)
            {
                resultList = await _context.Joke
                    .Where(i => i.Owner == User.FindFirst(ClaimTypes.Email).Value.ToString())
                    .OrderBy(j =>j.Id)
                    .ToListAsync();//先撈取自己所創建的
                var tempList = await _context.Joke
                    .Where(i => i.Owner != Convert.ToString(User.FindFirst(ClaimTypes.Email).Value))
                    .OrderBy(j => j.Id)
                    .ToListAsync();
                resultList = resultList.Concat(tempList).ToList();
            }
            else
            {
                resultList = await _context.Joke.ToListAsync();
            }

            if(TempData["Message"] is not null and not (object?)"")
            {
                var message = TempData["Message"] as string;
                ViewBag.Message = message;
            }
            
            return _context.Joke != null ? 
                View(resultList) :
                Problem("Entity set 'MyWebAppDbContext.Joke'  is null.");
        }

        public IActionResult ShowSearchForm()
        {
            return View();
                        
        }

        [HttpPost]
        public async Task<IActionResult> ShowSearchResults(string SearchPhrase)//搜尋笑話
        {
            Console.WriteLine("搜尋字串為：" + SearchPhrase);
            ViewBag.SearchPhrase = SearchPhrase;
            return View("Index", await _context.Joke.Where(j => j.JokeQuestion.Contains(SearchPhrase)).ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Joke == null)
            {
                return NotFound();
            }

            var joke = await _context.Joke
                .FirstOrDefaultAsync(m => m.Id == id);
            if (joke == null)
            {
                return NotFound();
            }

            return View(joke);
        }

        [Authorize]
        public IActionResult Create()
        {
            if (User.Identity.IsAuthenticated)
            {
                Console.WriteLine("前往創建JOKE畫面");
                return View();
            }
            else
            {
                Console.WriteLine("需先會員登入才能創建JOKE");
                return RedirectToAction(nameof(MembersController.Login), "Members");
            }
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(/*[Bind("Id,JokeQuestion,JokeAnswer")]*/ Joke joke)
        {
            //joke.Owner = User.Identity.Name.ToString();
            joke.Owner = User.FindFirst(ClaimTypes.Email).Value.ToString();
            var isSuccess = false;
            //if (ModelState.IsValid)
            //{
            //    _context.Add(joke);
            //    await _context.SaveChangesAsync();
            //    return RedirectToAction(nameof(Index));
            //}
            try
            {
                _context.Add(joke);
                await _context.SaveChangesAsync();
                isSuccess = true;
                //ViewBag.Message = "創建成功！";
                TempData["Message"] = "創建成功！";
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }
            finally
            {

            }
            return isSuccess == true ? RedirectToAction(nameof(Index)) : View(joke);
        }

        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Joke == null)
            {
                return NotFound();
            }

            var joke = await _context.Joke.FindAsync(id);
            if (joke == null)
            {
                return NotFound();
            }
            return View(joke);
        }


        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,JokeQuestion,JokeAnswer")] Joke joke)
        {
            if (id != joke.Id)
            {
                return NotFound();
            }

            bool isSuccess = false;

            try
            {
                var entity = _context.Joke.Find(joke.Id);
                var entry = _context.Entry(entity);
                entry.CurrentValues.SetValues(new { JokeQuestion = joke.JokeQuestion, JokeAnswer = joke.JokeAnswer });
                await _context.SaveChangesAsync();
                isSuccess = true;
            }
            catch(Exception ex)
            {
                Console.WriteLine(ex.Message);
                //isSuccess = false;
            }
            finally
            {

            }
            //if (ModelState.IsValid)
            //{
            //    try
            //    {
            //        _context.Update(joke);
            //        await _context.SaveChangesAsync();
            //        //ViewBag.Message = "修改成功！";
            //        TempData["Message"] = "修改成功！";
            //    }
            //    catch (DbUpdateConcurrencyException)
            //    {
            //        if (!JokeExists(joke.Id))
            //        {
            //            return NotFound();
            //        }
            //        else
            //        {
            //            throw;
            //        }
            //    }
            //    return RedirectToAction(nameof(Index));
            //}
            if (isSuccess)
            {
                return RedirectToAction(nameof(Index));
            }
            return View(joke);
        }

        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Joke == null)
            {
                return NotFound();
            }

            var joke = await _context.Joke
                .FirstOrDefaultAsync(m => m.Id == id);
            if (joke == null)
            {
                return NotFound();
            }

            return View(joke);
        }

        [HttpPost, ActionName("Delete")]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Joke == null)
            {
                return Problem("Entity set 'MyWebAppDbContext.Joke'  is null.");
            }
            var joke = await _context.Joke.FindAsync(id);
            if (joke != null)
            {
                _context.Joke.Remove(joke);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool JokeExists(int id)
        {
          return (_context.Joke?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

MyWebApp/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Drawing.Printing;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyWebApp.Data;
using MyWebApp.Models;
using MyWebApp.Services;

namespace MyWebApp.Controllers
{
    public class ProductsController : Controller
    {
        private readonly MyWebAppDbContext _context;
        private readonly ProductService _productService;
        private int pageSize;//1頁顯示的商品數量

        public ProductsController(MyWebAppDbContext context, ProductService productService)
        {
            _context = context;
            _productService = productService;
            pageSize = 6;
        }

        public async Task<IActionResult> Index(string? page, string? productCategory, string? searchPhrase)//商品頁面
        {
            int totalProducts = 0;
            int totalPages = 0;
            IEnumerable<Product> productsToShow = new List<Product>();
            if (page == null)
            {
                page = "1";
            }
            if(productCategory == null || productCategory == "")
            {
                productCategory = "all";
            }
            if(searchPhrase == null)
            {
                List<Product> products = await _productService.PageGetProducts(Convert.ToInt32(page), pageSize, productCategory);
                totalProducts = products.Count();//商品總數
                totalPages = (int)Math.Ceiling((double)totalProducts / pageSize);//商品總頁數
                productsToShow = products.Skip((Convert.ToInt32(page) - 1) * pageSize).Take(pageSize);//分頁查詢，取出指定頁數的商品
            }
            else
            {
                return RedirectToAction("Search", new {page = Convert.ToInt32(page), search = searchPhrase });
            }
            

            ViewBag.pageSize = pageSize;//一頁顯示的商品數
            ViewBag.currentPage = Convert.ToInt32(page);//傳遞當前頁數
            ViewBag.totalPages = totalPages;//傳遞總頁數
            ViewBag.productCategory = productCategory;//傳遞搜尋商品類別
            if(searchPhrase != null)
            {
                ViewBag.searchPhrase = searchPhrase;
            }
            
            if (TempData["Message"] is not null and not (object?)"")
            {
                ViewBag.Message = TempData["Message"];
            }

            return View(productsToShow);

        }

        public IActionResult IndexApi()
        {
            return View();
        }

        

        [HttpGet]
        public async Task<IActionResult> Search(int page, string search)
        {
            Console.WriteLine("搜尋字串為：" + search);
            //int page = 1;
            List<Product> products = await _productService.PageGetProducts(page, pageSize, "all", search);
            int totalProducts = products.Count();//商品總數
            int totalPages = (int)Math.Ceiling((double)totalProducts / pageSize);//商品總頁數
            var productsToShow = products.Skip((Convert.ToInt32(page) - 1) * pageSize).Take(pageSize);//分頁查詢，取出指定頁數的商品

            ViewBag.pageSize = pageSize;//一頁顯示的商品數
            ViewBag.currentPage = Convert.ToInt32(page);//傳遞當前頁數
            ViewBag.totalPages = totalPages;//傳遞總頁數
            ViewBag.productCategory = "all";//傳遞搜尋商品類別
            ViewBag.searchPhrase = search;
            return View("Index", productsToShow);
        }


        [Authorize]
        public async Task<IActionResult> WishlistPage()
        {
            if (User.Identity.IsAuthenticated)
            {
                int id = Convert.ToInt32(User.FindFirst(ClaimTypes.Sid).Value);

                return View(await _productService.MemberToWishlistPage(id));
            }
            TempData["Message"] = "需先登入會員";
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> ProductPage(string id)
        {
            return View(await _productService.ProductPage(Convert.ToInt32(id)));
        }

        [Authorize]
        public async Task<string> AddWishlist(string id)//加入願望清單
        {
            return await _productService.AddWishlist(Convert.ToInt32(id), Convert.ToInt32(User.FindFirst(ClaimTypes.Sid).Value));
        }

        public async Task<string> DeleteFromWishlist(int id)
        {
            return await _productService.DeleteFromWishlist(id, Convert.ToInt32(User.FindFirst(ClaimTypes.Sid).Value));
        }
    }
}

MyWebApp/Views/Members/Delete.cshtml
@model MyWebApp.Models.Member

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Member</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MyWebApp/Views/Members/Details.cshtml
@model MyWebApp.Models.Member

@{
    ViewData["Title"] = "Details";
}
<div class="b-example-divider"></div>
<div class="container">
    <h1>會員資料查看</h1>

    <div>
        <h4>Member</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Email)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Email)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Password)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Password)
            </dd>
        </dl>
    </div>
    <div>
        <a asp-action="Edit" asp-route-id="@Model?.Id">修改資料</a> |
        <a asp-action="Index">回首頁</a>
    </div>
</div>

MyWebApp/Views/Members/Edit.cshtml
@model MyWebApp.Models.Member

@{
    ViewData["Title"] = "Edit";
}
<div class="b-example-divider"></div>
<div class="container">
    <h1>修改會員資料</h1>

    <!--<h4>Member</h4>-->
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Email" class="control-label"></label>
                    <input readonly asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Password" class="control-label"></label>
                    <input asp-for="Password" class="form-control" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="確認修改" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">回會員首頁</a>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<script>
    function showMessage() {
    @*var message = '@ViewBag.Message.ToString()';*@
            var message = $("#Message").val();
        if (message != null && message != "") {
            alert(message);
        }
        console.log(message);
    }

    window.onload = function () {
        showMessage();
    };
</script>

MyWebApp/Views/Members/Index.cshtml
@model IEnumerable<MyWebApp.Models.Member>

@{
    ViewData["Title"] = "Index";
}

<div>
    <input type="hidden" value="@ViewBag.Message" id="Message" />
    @*<input type="hidden" value="@ViewBag.CookieValue" id="CookieValue" />*@
</div>
<div class="b-example-divider"></div>
<div class="container">
    <h1>會員首頁</h1>

    歡迎回來，@User.Identity.Name</br>
    功能列表：<br />
    <a class="btn btn-link" asp-area="" asp-controller="Members" asp-action="Details">查看會員資料</a>
    <a class="btn btn-link" asp-area="" asp-controller="Jokes" asp-action="Index">YouTube教學影片：JOCK笑話分享</a>
    <a class="btn btn-link" asp-area="" asp-controller="Products" asp-action="Index">商品</a>
    <hr />
    <p id="showCookieValue"></p>
</div>

<script>

    function showMessage() {
        @*var message = '@ViewBag.Message.ToString()';*@
        var message = $("#Message").val();
        if (message != null && message != "") {
            alert(message);
        }
        console.log(message);
    }

    function showCookieValue(){
        //if ($("#CookieValue").val() == "" ){
        //    $("#showCookieValue").text($("#CookieValue").val());
        //}
    }

    window.onload = function () {
        showMessage();
        showCookieValue();
    };

</script>

MyWebApp/Views/Members/Login.cshtml
<div class="b-example-divider"></div>
<div class="container">
    <h4>會員登入</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Login">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label for="Email" class="control-label">Email</label>
                    <input name="Email" class="form-control" type="email" />
                </div>
                <div class="form-group">
                    <label for="Password" class="control-label">Password</label>
                    <input name="Password" class="form-control" type="password" />
                </div>
                <div class="form-group">
                    <input type="submit" value="登入" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">回首頁</a>
    </div>
</di>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<script>

    function showMessage() {
        @*var message = '@ViewBag.Message.ToString()';*@
        var message = $("#Message").val();
        if (message != null && message != "") {
            alert(message);
        }
        console.log(message);
    }

    window.onload = function () {
        showMessage();
    };

</script>

MyWebApp/Views/Members/Register.cshtml
@model MyWebApp.Models.Member

@{
    ViewData["Title"] = "Register";
    ViewData["CTitle"] = "會員註冊";
}
<div class="b-example-divider"></div>
<div class="container">
    <h1>@ViewData["CTitle"]</h1>
    <hr />
    <div>
        <input type="hidden" value="@ViewBag.Message" id="Message" />
    </div>
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Register">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label">輸入姓名：</label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Email" class="control-label">輸入Email：</label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Password" class="control-label">輸入密碼：</label>
                    <input asp-for="Password" class="form-control" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="hidden" value="member" asp-for="Role" class="form-control" />
                    <span asp-validation-for="Role" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="註冊會員" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">回首頁</a>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<script>
    
    function showMessage() {
        @*var message = '@ViewBag.Message.ToString()';*@
        var message = $("#Message").val();
        if (message != null && message != "") {
            alert(message);
        }
        console.log(message);
    }

    window.onload = function () {
        showMessage();
    };
</script>